### ISSUE TITLE
failed to locate '@import typus'

### ISSUE THREAD

**Issue by dam0** [rayfranco/typus#2] opened 2016-10-21 09:14 UTC
When building Bourgeon app boilerplate, web pack errors with 
"failed to locate @import file typus.styl"  -  

typus is installed in .node_modules & build works when path is referenced as: "@import "../typus"
(so guess thats a Bourgeon issue)

`32| <style lang="stylus">
   33| @import "typus" // base styles
---------------^
   34| 
   35| html
   36|   +below(600px) // rupture

failed to locate @import file typus.styl`

**Comment by rayfranco** [comment] 2016-10-21 12:20
@dam0 that sounds more like a problem with webpack resolving `node_modules` packages. I can't reproduce this though. What is your setup?

**Comment by dam0** [comment] 2016-10-25 18:26
Sure, sounds like webpack. I’m using OSX, latest npm 4, node 6.8.1, and bourgeon (https://github.com/rayfranco/bourgeon)

**Comment by rayfranco** [comment] 2017-03-13 16:26
@dam0 this issue was related to Bourgeon and has been fixed in the version **2.3.0**. Thanks for reporting.

**Closed by rayfranco** 2017-03-13 16:26 UTC
Labels: bug
